set(CMAKE_C_FLAGS_RELEASE "-O2")
set(CMAKE_CXX_FLAGS_RELEASE "-O2")

set(CMAKE_C_FLAGS_DEBUG "-g -D_DEBUG")
set(CMAKE_CXX_FLAGS_DEBUG "-g -D_DEBUG")

if(CMAKE_BUILD_TYPE STREQUAL Release)

  set(CMAKE_C_FLAGS "${PLATFORM_CFLAGS} ${CMAKE_C_FLAGS_RELEASE} ${CMAKE_C_FLAGS}")
  set(CMAKE_CXX_FLAGS "${PLATFORM_CXXFLAGS} ${CMAKE_CXX_FLAGS_RELEASE} ${CMAKE_CXX_FLAGS}")

elseif(CMAKE_BUILD_TYPE STREQUAL Debug)

  set(CMAKE_C_FLAGS "${PLATFORM_CFLAGS} ${CMAKE_C_FLAGS_DEBUG} ${CMAKE_C_FLAGS}")
  set(CMAKE_CXX_FLAGS "${PLATFORM_CXXFLAGS} ${CMAKE_CXX_FLAGS_DEBUG} ${CMAKE_CXX_FLAGS}")

endif()

set(CMAKE_EXE_LINKER_FLAGS "${PLATFORM_LDFLAGS} ${CMAKE_EXE_LINKER_FLAGS}")
set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS}")
set(CMAKE_MODULE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS}")
